name: Metrics

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Asmit1434
          template: classic
          output: metrics
          base: half,rim,header
          config_timezone: Asia/Kolkata
          plugin_languages: true
          plugin_languages_limit: 12
          plugin_languages_details: true
          plugin_isocalendar: true
          plugin_isocalendar_duration: half-year
          plugin_habits: true
          plugin_habits_charts: true
          plugin_habits_facts: true
          plugin_achievements: true
          plugin_lines: true
          plugin_topics: true
          plugin_topics_limit: 12
          plugin_repositories: true
          plugin_repositories_pinned: 6

      - name: Deploy metrics
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: metrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
