name: Metrics

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate metrics (base)
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Asmit1434
          template: classic
          base: half,rim,header
          config_timezone: Asia/Kolkata

      - name: Generate metrics (languages)
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Asmit1434
          template: classic
          plugin_languages: true
          plugin_languages_limit: 12
          plugin_languages_details: true

      - name: Generate metrics (isometric calendar)
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Asmit1434
          template: classic
          plugin_isocalendar: true
          plugin_isocalendar_duration: half-year

      - name: Generate metrics (habits)
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Asmit1434
          template: classic
          plugin_habits: true
          plugin_habits_charts: true
          plugin_habits_facts: true

      - name: Generate metrics (achievements)
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Asmit1434
          template: classic
          plugin_achievements: true

      - name: Generate metrics (lines of code)
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Asmit1434
          template: classic
          plugin_lines: true

      - name: Generate metrics (topics)
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Asmit1434
          template: classic
          plugin_topics: true
          plugin_topics_limit: 12

      - name: Generate metrics (repositories)
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Asmit1434
          template: classic
          plugin_repositories: true
          plugin_repositories_pinned: 6

      - name: Deploy metrics
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: metrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
